-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Libros"
(
    codigo_libro integer NOT NULL DEFAULT nextval('"Libros_id_libro_seq"'::regclass),
    titulo character varying(200) COLLATE pg_catalog."default" NOT NULL,
    genero character varying(200) COLLATE pg_catalog."default" NOT NULL,
    fecha_publicacion date NOT NULL,
    autor character varying(200) COLLATE pg_catalog."default" NOT NULL,
    editorial character varying(200) COLLATE pg_catalog."default" NOT NULL,
    edicion character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Libros_pkey" PRIMARY KEY (codigo_libro)
);

CREATE TABLE IF NOT EXISTS public."Personas"
(
    codigo_persona serial NOT NULL,
    nombre character varying(200) COLLATE pg_catalog."default" NOT NULL,
    apellido character varying(200) COLLATE pg_catalog."default" NOT NULL,
    cedula character varying(200) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(200) COLLATE pg_catalog."default" NOT NULL,
    correo character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Personas_pkey" PRIMARY KEY (codigo_persona)
);

CREATE TABLE IF NOT EXISTS public."Préstamos"
(
    id serial NOT NULL,
    codigo_libro integer NOT NULL,
    codigo_persona integer NOT NULL,
    codigo_usuario integer NOT NULL,
    fecha_entrega date NOT NULL,
    fecha_devolucion date NOT NULL,
    CONSTRAINT "Préstamos_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Usuarios"
(
    codigo_usuario serial NOT NULL,
    usuario character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "contraseña" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    rol character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Usuarios_pkey" PRIMARY KEY (codigo_usuario)
);

ALTER TABLE IF EXISTS public."Préstamos"
    ADD CONSTRAINT cf_01 FOREIGN KEY (codigo_libro)
    REFERENCES public."Libros" (codigo_libro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

COMMENT ON CONSTRAINT cf_01 ON public."Préstamos"
    IS 'Clave foránea de lo contenido en la tabla libros';



ALTER TABLE IF EXISTS public."Préstamos"
    ADD CONSTRAINT cf_02 FOREIGN KEY (codigo_persona)
    REFERENCES public."Personas" (codigo_persona) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

COMMENT ON CONSTRAINT cf_02 ON public."Préstamos"
    IS 'Clave foránea de lo contenido en la tabla personas ';



ALTER TABLE IF EXISTS public."Préstamos"
    ADD CONSTRAINT cf_03 FOREIGN KEY (codigo_usuario)
    REFERENCES public."Usuarios" (codigo_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

COMMENT ON CONSTRAINT cf_03 ON public."Préstamos"
    IS 'Clave foránea de lo contenido en la tabla usuarios';


END;